# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         libYperl
version:      0.0.3
version_from: lib/Y.pm
installdirs:  site
requires:
    POE:                           0.27
    WeakRef:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
