## Autogenerated from Y/const.h ##
package Y::Constants;

use strict;
use vars qw(@ISA @EXPORT_OK %EXPORT_TAGS @keys @messages @modifiers);

require Exporter;
@ISA = qw(Exporter);

sub YMO_NO_OPERATION () { 0 }
push @messages, "YMO_NO_OPERATION";
sub YMO_ERROR () { 1 }
push @messages, "YMO_ERROR";
sub YMO_QUIT () { 2 }
push @messages, "YMO_QUIT";
sub YMO_EVENT () { 3 }
push @messages, "YMO_EVENT";
sub YMO_INVOKE_SPECIAL () { 4 }
push @messages, "YMO_INVOKE_SPECIAL";
sub YMO_SPECIAL_RETURNS () { 5 }
push @messages, "YMO_SPECIAL_RETURNS";
sub YMO_FIND_CLASS () { 6 }
push @messages, "YMO_FIND_CLASS";
sub YMO_FOUND_CLASS () { 7 }
push @messages, "YMO_FOUND_CLASS";
sub YMO_INSTANTIATE () { 8 }
push @messages, "YMO_INSTANTIATE";
sub YMO_NEW_OBJECT () { 9 }
push @messages, "YMO_NEW_OBJECT";
sub YMO_INVOKE_METHOD () { 10 }
push @messages, "YMO_INVOKE_METHOD";
sub YMO_METHOD_RETURNS () { 11 }
push @messages, "YMO_METHOD_RETURNS";
sub YMO_GET_PROPERTY () { 12 }
push @messages, "YMO_GET_PROPERTY";
sub YMO_GOT_PROPERTY () { 13 }
push @messages, "YMO_GOT_PROPERTY";
sub YMO_SET_PROPERTY () { 14 }
push @messages, "YMO_SET_PROPERTY";
sub YMO_SUBSCRIBE_SIGNAL () { 15 }
push @messages, "YMO_SUBSCRIBE_SIGNAL";
sub YMO_LIST_METHODS () { 16 }
push @messages, "YMO_LIST_METHODS";
sub YMO_METHODS_LISTED () { 17 }
push @messages, "YMO_METHODS_LISTED";
sub YMO_LIST_PROPERTIES () { 18 }
push @messages, "YMO_LIST_PROPERTIES";
sub YMO_PROPERTIES_LISTED () { 19 }
push @messages, "YMO_PROPERTIES_LISTED";

sub YK_UNKNOWN () { 0 }
push @keys, "YK_UNKNOWN";
sub YK_FIRST () { 0 }
push @keys, "YK_FIRST";
sub YK_CTRL_A () { 1 }
push @keys, "YK_CTRL_A";
sub YK_CTRL_B () { 2 }
push @keys, "YK_CTRL_B";
sub YK_CTRL_C () { 3 }
push @keys, "YK_CTRL_C";
sub YK_CTRL_D () { 4 }
push @keys, "YK_CTRL_D";
sub YK_CTRL_E () { 5 }
push @keys, "YK_CTRL_E";
sub YK_CTRL_F () { 6 }
push @keys, "YK_CTRL_F";
sub YK_CTRL_G () { 7 }
push @keys, "YK_CTRL_G";
sub YK_CTRL_H () { 8 }
push @keys, "YK_CTRL_H";
sub YK_BACKSPACE () { 8 }
push @keys, "YK_BACKSPACE";
sub YK_CTRL_I () { 9 }
push @keys, "YK_CTRL_I";
sub YK_TAB () { 9 }
push @keys, "YK_TAB";
sub YK_CTRL_J () { 10 }
push @keys, "YK_CTRL_J";
sub YK_CTRL_K () { 11 }
push @keys, "YK_CTRL_K";
sub YK_CTRL_L () { 12 }
push @keys, "YK_CTRL_L";
sub YK_CLEAR () { 12 }
push @keys, "YK_CLEAR";
sub YK_CTRL_M () { 13 }
push @keys, "YK_CTRL_M";
sub YK_RETURN () { 13 }
push @keys, "YK_RETURN";
sub YK_CTRL_N () { 14 }
push @keys, "YK_CTRL_N";
sub YK_CTRL_O () { 15 }
push @keys, "YK_CTRL_O";
sub YK_CTRL_P () { 16 }
push @keys, "YK_CTRL_P";
sub YK_CTRL_Q () { 17 }
push @keys, "YK_CTRL_Q";
sub YK_CTRL_R () { 18 }
push @keys, "YK_CTRL_R";
sub YK_CTRL_S () { 19 }
push @keys, "YK_CTRL_S";
sub YK_PAUSE () { 19 }
push @keys, "YK_PAUSE";
sub YK_CTRL_T () { 20 }
push @keys, "YK_CTRL_T";
sub YK_CTRL_U () { 21 }
push @keys, "YK_CTRL_U";
sub YK_CTRL_V () { 22 }
push @keys, "YK_CTRL_V";
sub YK_CTRL_W () { 23 }
push @keys, "YK_CTRL_W";
sub YK_CTRL_X () { 24 }
push @keys, "YK_CTRL_X";
sub YK_CTRL_Y () { 25 }
push @keys, "YK_CTRL_Y";
sub YK_CTRL_Z () { 26 }
push @keys, "YK_CTRL_Z";
sub YK_CTRL_LEFTBRACKET () { 27 }
push @keys, "YK_CTRL_LEFTBRACKET";
sub YK_ESCAPE () { 27 }
push @keys, "YK_ESCAPE";
sub YK_CTRL_BACKSLASH () { 28 }
push @keys, "YK_CTRL_BACKSLASH";
sub YK_CTRL_RIGHTBRACKET () { 29 }
push @keys, "YK_CTRL_RIGHTBRACKET";
sub YK_CTRL_CARET () { 30 }
push @keys, "YK_CTRL_CARET";
sub YK_CTRL_UNDERSCORE () { 31 }
push @keys, "YK_CTRL_UNDERSCORE";
sub YK_SPACE () { 32 }
push @keys, "YK_SPACE";
sub YK_EXCLAIM () { 33 }
push @keys, "YK_EXCLAIM";
sub YK_QUOTEDBL () { 34 }
push @keys, "YK_QUOTEDBL";
sub YK_HASH () { 35 }
push @keys, "YK_HASH";
sub YK_DOLLAR () { 36 }
push @keys, "YK_DOLLAR";
sub YK_PERCENT () { 37 }
push @keys, "YK_PERCENT";
sub YK_AMPERSAND () { 38 }
push @keys, "YK_AMPERSAND";
sub YK_QUOTE () { 39 }
push @keys, "YK_QUOTE";
sub YK_LEFTPAREN () { 40 }
push @keys, "YK_LEFTPAREN";
sub YK_RIGHTPAREN () { 41 }
push @keys, "YK_RIGHTPAREN";
sub YK_ASTERISK () { 42 }
push @keys, "YK_ASTERISK";
sub YK_PLUS () { 43 }
push @keys, "YK_PLUS";
sub YK_COMMA () { 44 }
push @keys, "YK_COMMA";
sub YK_MINUS () { 45 }
push @keys, "YK_MINUS";
sub YK_PERIOD () { 46 }
push @keys, "YK_PERIOD";
sub YK_SLASH () { 47 }
push @keys, "YK_SLASH";
sub YK_0 () { 48 }
push @keys, "YK_0";
sub YK_1 () { 49 }
push @keys, "YK_1";
sub YK_2 () { 50 }
push @keys, "YK_2";
sub YK_3 () { 51 }
push @keys, "YK_3";
sub YK_4 () { 52 }
push @keys, "YK_4";
sub YK_5 () { 53 }
push @keys, "YK_5";
sub YK_6 () { 54 }
push @keys, "YK_6";
sub YK_7 () { 55 }
push @keys, "YK_7";
sub YK_8 () { 56 }
push @keys, "YK_8";
sub YK_9 () { 57 }
push @keys, "YK_9";
sub YK_COLON () { 58 }
push @keys, "YK_COLON";
sub YK_SEMICOLON () { 59 }
push @keys, "YK_SEMICOLON";
sub YK_LESS () { 60 }
push @keys, "YK_LESS";
sub YK_EQUALS () { 61 }
push @keys, "YK_EQUALS";
sub YK_GREATER () { 62 }
push @keys, "YK_GREATER";
sub YK_QUESTION () { 63 }
push @keys, "YK_QUESTION";
sub YK_AT () { 64 }
push @keys, "YK_AT";
sub YK_A () { 65 }
push @keys, "YK_A";
sub YK_B () { 66 }
push @keys, "YK_B";
sub YK_C () { 67 }
push @keys, "YK_C";
sub YK_D () { 68 }
push @keys, "YK_D";
sub YK_E () { 69 }
push @keys, "YK_E";
sub YK_F () { 70 }
push @keys, "YK_F";
sub YK_G () { 71 }
push @keys, "YK_G";
sub YK_H () { 72 }
push @keys, "YK_H";
sub YK_I () { 73 }
push @keys, "YK_I";
sub YK_J () { 74 }
push @keys, "YK_J";
sub YK_K () { 75 }
push @keys, "YK_K";
sub YK_L () { 76 }
push @keys, "YK_L";
sub YK_M () { 77 }
push @keys, "YK_M";
sub YK_N () { 78 }
push @keys, "YK_N";
sub YK_O () { 79 }
push @keys, "YK_O";
sub YK_P () { 80 }
push @keys, "YK_P";
sub YK_Q () { 81 }
push @keys, "YK_Q";
sub YK_R () { 82 }
push @keys, "YK_R";
sub YK_S () { 83 }
push @keys, "YK_S";
sub YK_T () { 84 }
push @keys, "YK_T";
sub YK_U () { 85 }
push @keys, "YK_U";
sub YK_V () { 86 }
push @keys, "YK_V";
sub YK_W () { 87 }
push @keys, "YK_W";
sub YK_X () { 88 }
push @keys, "YK_X";
sub YK_Y () { 89 }
push @keys, "YK_Y";
sub YK_Z () { 90 }
push @keys, "YK_Z";
sub YK_LEFTBRACKET () { 91 }
push @keys, "YK_LEFTBRACKET";
sub YK_BACKSLASH () { 92 }
push @keys, "YK_BACKSLASH";
sub YK_RIGHTBRACKET () { 93 }
push @keys, "YK_RIGHTBRACKET";
sub YK_CARET () { 94 }
push @keys, "YK_CARET";
sub YK_UNDERSCORE () { 95 }
push @keys, "YK_UNDERSCORE";
sub YK_BACKQUOTE () { 96 }
push @keys, "YK_BACKQUOTE";
sub YK_a () { 97 }
push @keys, "YK_a";
sub YK_b () { 98 }
push @keys, "YK_b";
sub YK_c () { 99 }
push @keys, "YK_c";
sub YK_d () { 100 }
push @keys, "YK_d";
sub YK_e () { 101 }
push @keys, "YK_e";
sub YK_f () { 102 }
push @keys, "YK_f";
sub YK_g () { 103 }
push @keys, "YK_g";
sub YK_h () { 104 }
push @keys, "YK_h";
sub YK_i () { 105 }
push @keys, "YK_i";
sub YK_j () { 106 }
push @keys, "YK_j";
sub YK_k () { 107 }
push @keys, "YK_k";
sub YK_l () { 108 }
push @keys, "YK_l";
sub YK_m () { 109 }
push @keys, "YK_m";
sub YK_n () { 110 }
push @keys, "YK_n";
sub YK_o () { 111 }
push @keys, "YK_o";
sub YK_p () { 112 }
push @keys, "YK_p";
sub YK_q () { 113 }
push @keys, "YK_q";
sub YK_r () { 114 }
push @keys, "YK_r";
sub YK_s () { 115 }
push @keys, "YK_s";
sub YK_t () { 116 }
push @keys, "YK_t";
sub YK_u () { 117 }
push @keys, "YK_u";
sub YK_v () { 118 }
push @keys, "YK_v";
sub YK_w () { 119 }
push @keys, "YK_w";
sub YK_x () { 120 }
push @keys, "YK_x";
sub YK_y () { 121 }
push @keys, "YK_y";
sub YK_z () { 122 }
push @keys, "YK_z";
sub YK_LEFTBRACE () { 123 }
push @keys, "YK_LEFTBRACE";
sub YK_PIPE () { 124 }
push @keys, "YK_PIPE";
sub YK_RIGHTBRACE () { 125 }
push @keys, "YK_RIGHTBRACE";
sub YK_TILDE () { 126 }
push @keys, "YK_TILDE";
sub YK_DELETE () { 127 }
push @keys, "YK_DELETE";

sub YK_WORLD_0 () { 160 }
push @keys, "YK_WORLD_0";
sub YK_WORLD_1 () { 161 }
push @keys, "YK_WORLD_1";
sub YK_WORLD_2 () { 162 }
push @keys, "YK_WORLD_2";
sub YK_WORLD_3 () { 163 }
push @keys, "YK_WORLD_3";
sub YK_WORLD_4 () { 164 }
push @keys, "YK_WORLD_4";
sub YK_WORLD_5 () { 165 }
push @keys, "YK_WORLD_5";
sub YK_WORLD_6 () { 166 }
push @keys, "YK_WORLD_6";
sub YK_WORLD_7 () { 167 }
push @keys, "YK_WORLD_7";
sub YK_WORLD_8 () { 168 }
push @keys, "YK_WORLD_8";
sub YK_WORLD_9 () { 169 }
push @keys, "YK_WORLD_9";
sub YK_WORLD_10 () { 170 }
push @keys, "YK_WORLD_10";
sub YK_WORLD_11 () { 171 }
push @keys, "YK_WORLD_11";
sub YK_WORLD_12 () { 172 }
push @keys, "YK_WORLD_12";
sub YK_WORLD_13 () { 173 }
push @keys, "YK_WORLD_13";
sub YK_WORLD_14 () { 174 }
push @keys, "YK_WORLD_14";
sub YK_WORLD_15 () { 175 }
push @keys, "YK_WORLD_15";
sub YK_WORLD_16 () { 176 }
push @keys, "YK_WORLD_16";
sub YK_WORLD_17 () { 177 }
push @keys, "YK_WORLD_17";
sub YK_WORLD_18 () { 178 }
push @keys, "YK_WORLD_18";
sub YK_WORLD_19 () { 179 }
push @keys, "YK_WORLD_19";
sub YK_WORLD_20 () { 180 }
push @keys, "YK_WORLD_20";
sub YK_WORLD_21 () { 181 }
push @keys, "YK_WORLD_21";
sub YK_WORLD_22 () { 182 }
push @keys, "YK_WORLD_22";
sub YK_WORLD_23 () { 183 }
push @keys, "YK_WORLD_23";
sub YK_WORLD_24 () { 184 }
push @keys, "YK_WORLD_24";
sub YK_WORLD_25 () { 185 }
push @keys, "YK_WORLD_25";
sub YK_WORLD_26 () { 186 }
push @keys, "YK_WORLD_26";
sub YK_WORLD_27 () { 187 }
push @keys, "YK_WORLD_27";
sub YK_WORLD_28 () { 188 }
push @keys, "YK_WORLD_28";
sub YK_WORLD_29 () { 189 }
push @keys, "YK_WORLD_29";
sub YK_WORLD_30 () { 190 }
push @keys, "YK_WORLD_30";
sub YK_WORLD_31 () { 191 }
push @keys, "YK_WORLD_31";
sub YK_WORLD_32 () { 192 }
push @keys, "YK_WORLD_32";
sub YK_WORLD_33 () { 193 }
push @keys, "YK_WORLD_33";
sub YK_WORLD_34 () { 194 }
push @keys, "YK_WORLD_34";
sub YK_WORLD_35 () { 195 }
push @keys, "YK_WORLD_35";
sub YK_WORLD_36 () { 196 }
push @keys, "YK_WORLD_36";
sub YK_WORLD_37 () { 197 }
push @keys, "YK_WORLD_37";
sub YK_WORLD_38 () { 198 }
push @keys, "YK_WORLD_38";
sub YK_WORLD_39 () { 199 }
push @keys, "YK_WORLD_39";
sub YK_WORLD_40 () { 200 }
push @keys, "YK_WORLD_40";
sub YK_WORLD_41 () { 201 }
push @keys, "YK_WORLD_41";
sub YK_WORLD_42 () { 202 }
push @keys, "YK_WORLD_42";
sub YK_WORLD_43 () { 203 }
push @keys, "YK_WORLD_43";
sub YK_WORLD_44 () { 204 }
push @keys, "YK_WORLD_44";
sub YK_WORLD_45 () { 205 }
push @keys, "YK_WORLD_45";
sub YK_WORLD_46 () { 206 }
push @keys, "YK_WORLD_46";
sub YK_WORLD_47 () { 207 }
push @keys, "YK_WORLD_47";
sub YK_WORLD_48 () { 208 }
push @keys, "YK_WORLD_48";
sub YK_WORLD_49 () { 209 }
push @keys, "YK_WORLD_49";
sub YK_WORLD_50 () { 210 }
push @keys, "YK_WORLD_50";
sub YK_WORLD_51 () { 211 }
push @keys, "YK_WORLD_51";
sub YK_WORLD_52 () { 212 }
push @keys, "YK_WORLD_52";
sub YK_WORLD_53 () { 213 }
push @keys, "YK_WORLD_53";
sub YK_WORLD_54 () { 214 }
push @keys, "YK_WORLD_54";
sub YK_WORLD_55 () { 215 }
push @keys, "YK_WORLD_55";
sub YK_WORLD_56 () { 216 }
push @keys, "YK_WORLD_56";
sub YK_WORLD_57 () { 217 }
push @keys, "YK_WORLD_57";
sub YK_WORLD_58 () { 218 }
push @keys, "YK_WORLD_58";
sub YK_WORLD_59 () { 219 }
push @keys, "YK_WORLD_59";
sub YK_WORLD_60 () { 220 }
push @keys, "YK_WORLD_60";
sub YK_WORLD_61 () { 221 }
push @keys, "YK_WORLD_61";
sub YK_WORLD_62 () { 222 }
push @keys, "YK_WORLD_62";
sub YK_WORLD_63 () { 223 }
push @keys, "YK_WORLD_63";
sub YK_WORLD_64 () { 224 }
push @keys, "YK_WORLD_64";
sub YK_WORLD_65 () { 225 }
push @keys, "YK_WORLD_65";
sub YK_WORLD_66 () { 226 }
push @keys, "YK_WORLD_66";
sub YK_WORLD_67 () { 227 }
push @keys, "YK_WORLD_67";
sub YK_WORLD_68 () { 228 }
push @keys, "YK_WORLD_68";
sub YK_WORLD_69 () { 229 }
push @keys, "YK_WORLD_69";
sub YK_WORLD_70 () { 230 }
push @keys, "YK_WORLD_70";
sub YK_WORLD_71 () { 231 }
push @keys, "YK_WORLD_71";
sub YK_WORLD_72 () { 232 }
push @keys, "YK_WORLD_72";
sub YK_WORLD_73 () { 233 }
push @keys, "YK_WORLD_73";
sub YK_WORLD_74 () { 234 }
push @keys, "YK_WORLD_74";
sub YK_WORLD_75 () { 235 }
push @keys, "YK_WORLD_75";
sub YK_WORLD_76 () { 236 }
push @keys, "YK_WORLD_76";
sub YK_WORLD_77 () { 237 }
push @keys, "YK_WORLD_77";
sub YK_WORLD_78 () { 238 }
push @keys, "YK_WORLD_78";
sub YK_WORLD_79 () { 239 }
push @keys, "YK_WORLD_79";
sub YK_WORLD_80 () { 240 }
push @keys, "YK_WORLD_80";
sub YK_WORLD_81 () { 241 }
push @keys, "YK_WORLD_81";
sub YK_WORLD_82 () { 242 }
push @keys, "YK_WORLD_82";
sub YK_WORLD_83 () { 243 }
push @keys, "YK_WORLD_83";
sub YK_WORLD_84 () { 244 }
push @keys, "YK_WORLD_84";
sub YK_WORLD_85 () { 245 }
push @keys, "YK_WORLD_85";
sub YK_WORLD_86 () { 246 }
push @keys, "YK_WORLD_86";
sub YK_WORLD_87 () { 247 }
push @keys, "YK_WORLD_87";
sub YK_WORLD_88 () { 248 }
push @keys, "YK_WORLD_88";
sub YK_WORLD_89 () { 249 }
push @keys, "YK_WORLD_89";
sub YK_WORLD_90 () { 250 }
push @keys, "YK_WORLD_90";
sub YK_WORLD_91 () { 251 }
push @keys, "YK_WORLD_91";
sub YK_WORLD_92 () { 252 }
push @keys, "YK_WORLD_92";
sub YK_WORLD_93 () { 253 }
push @keys, "YK_WORLD_93";
sub YK_WORLD_94 () { 254 }
push @keys, "YK_WORLD_94";
sub YK_WORLD_95 () { 255 }
push @keys, "YK_WORLD_95";

sub YK_KP0 () { 256 }
push @keys, "YK_KP0";
sub YK_KP1 () { 257 }
push @keys, "YK_KP1";
sub YK_KP2 () { 258 }
push @keys, "YK_KP2";
sub YK_KP3 () { 259 }
push @keys, "YK_KP3";
sub YK_KP4 () { 260 }
push @keys, "YK_KP4";
sub YK_KP5 () { 261 }
push @keys, "YK_KP5";
sub YK_KP6 () { 262 }
push @keys, "YK_KP6";
sub YK_KP7 () { 263 }
push @keys, "YK_KP7";
sub YK_KP8 () { 264 }
push @keys, "YK_KP8";
sub YK_KP9 () { 265 }
push @keys, "YK_KP9";
sub YK_KP_PERIOD () { 266 }
push @keys, "YK_KP_PERIOD";
sub YK_KP_DIVIDE () { 267 }
push @keys, "YK_KP_DIVIDE";
sub YK_KP_MULTIPLY () { 268 }
push @keys, "YK_KP_MULTIPLY";
sub YK_KP_MINUS () { 269 }
push @keys, "YK_KP_MINUS";
sub YK_KP_PLUS () { 270 }
push @keys, "YK_KP_PLUS";
sub YK_KP_ENTER () { 271 }
push @keys, "YK_KP_ENTER";
sub YK_KP_EQUALS () { 272 }
push @keys, "YK_KP_EQUALS";

sub YK_UP () { 273 }
push @keys, "YK_UP";
sub YK_DOWN () { 274 }
push @keys, "YK_DOWN";
sub YK_RIGHT () { 275 }
push @keys, "YK_RIGHT";
sub YK_LEFT () { 276 }
push @keys, "YK_LEFT";
sub YK_INSERT () { 277 }
push @keys, "YK_INSERT";
sub YK_HOME () { 278 }
push @keys, "YK_HOME";
sub YK_END () { 279 }
push @keys, "YK_END";
sub YK_PAGEUP () { 280 }
push @keys, "YK_PAGEUP";
sub YK_PAGEDOWN () { 281 }
push @keys, "YK_PAGEDOWN";

sub YK_F1 () { 282 }
push @keys, "YK_F1";
sub YK_F2 () { 283 }
push @keys, "YK_F2";
sub YK_F3 () { 284 }
push @keys, "YK_F3";
sub YK_F4 () { 285 }
push @keys, "YK_F4";
sub YK_F5 () { 286 }
push @keys, "YK_F5";
sub YK_F6 () { 287 }
push @keys, "YK_F6";
sub YK_F7 () { 288 }
push @keys, "YK_F7";
sub YK_F8 () { 289 }
push @keys, "YK_F8";
sub YK_F9 () { 290 }
push @keys, "YK_F9";
sub YK_F10 () { 291 }
push @keys, "YK_F10";
sub YK_F11 () { 292 }
push @keys, "YK_F11";
sub YK_F12 () { 293 }
push @keys, "YK_F12";
sub YK_F13 () { 294 }
push @keys, "YK_F13";
sub YK_F14 () { 295 }
push @keys, "YK_F14";
sub YK_F15 () { 296 }
push @keys, "YK_F15";

sub YK_NUMLOCK () { 300 }
push @keys, "YK_NUMLOCK";
sub YK_CAPSLOCK () { 301 }
push @keys, "YK_CAPSLOCK";
sub YK_SCROLLLOCK () { 302 }
push @keys, "YK_SCROLLLOCK";
sub YK_RSHIFT () { 303 }
push @keys, "YK_RSHIFT";
sub YK_LSHIFT () { 304 }
push @keys, "YK_LSHIFT";
sub YK_RCTRL () { 305 }
push @keys, "YK_RCTRL";
sub YK_LCTRL () { 306 }
push @keys, "YK_LCTRL";
sub YK_RALT () { 307 }
push @keys, "YK_RALT";
sub YK_LALT () { 308 }
push @keys, "YK_LALT";
sub YK_RMETA () { 309 }
push @keys, "YK_RMETA";
sub YK_LMETA () { 310 }
push @keys, "YK_LMETA";
sub YK_LSUPER () { 311 }
push @keys, "YK_LSUPER";
sub YK_RSUPER () { 312 }
push @keys, "YK_RSUPER";
sub YK_MODE () { 313 }
push @keys, "YK_MODE";
sub YK_COMPOSE () { 314 }
push @keys, "YK_COMPOSE";

sub YK_HELP () { 315 }
push @keys, "YK_HELP";
sub YK_PRINT () { 316 }
push @keys, "YK_PRINT";
sub YK_SYSREQ () { 317 }
push @keys, "YK_SYSREQ";
sub YK_BREAK () { 318 }
push @keys, "YK_BREAK";
sub YK_MENU () { 319 }
push @keys, "YK_MENU";
sub YK_POWER () { 320 }
push @keys, "YK_POWER";
sub YK_EURO () { 321 }
push @keys, "YK_EURO";

sub YK_LAS () { 322 }
push @keys, "YK_LAS";

sub YMOD_NONE () { 0 }
push @modifiers, "YMOD_NONE";
sub YMOD_SHIFT () { 1 }
push @modifiers, "YMOD_SHIFT";
sub YMOD_CTRL () { 2 }
push @modifiers, "YMOD_CTRL";
sub YMOD_ALT () { 4 }
push @modifiers, "YMOD_ALT";
sub YMOD_META () { 16 }
push @modifiers, "YMOD_META";
sub YMOD_MODE () { 32 }
push @modifiers, "YMOD_MODE";
sub YMOD_NUMLOCK () { 64 }
push @modifiers, "YMOD_NUMLOCK";

%EXPORT_TAGS = (
    all       => [@messages, @keys, @modifiers],
    messages  => \@messages,
    modifiers => \@modifiers,
    keys      => \@keys,
);
@EXPORT_OK = (@messages, @keys, @modifiers);

1;

__END__

